server:
  servlet:
    context-path:  /ios-web
  port: 8886
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: @profileActive@

  # 设置文件可上传大小
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 500MB
  application:
    name: docios

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  mvc:
    pathmatch:
      matching:
        strategy: ant-path-matcher

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.yrnet.iosweb.business.entity,com.yrnet.iosweb.business.login.entity,com.yrnet.iosweb.system.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/register-center/eureka/


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间(毫秒)
ribbon:
  ReadTimeout: 90000
  ConnectTimeout: 90000

